POST http://127.0.0.1:8000/api/styles/
Content-Type: application/json

{
    "name": "New style",
    "type": "mixed"
}

###
POST http://localhost:8000/api/tasks
Content-Type: application/json

{
    "title": "string123",
    "color": "string123"
}
